# ==============================================================================
# TEMPLATE: ONE-OFF TASK / UTILITY SCRIPT
# PURPOSE : Executes a script to completion (backups, data sync, batch tasks) 
#           and returns control to the dashboard when finished.
# PLACE   : Place at "..\dashboard-options\<option-name>.ps1"
# ==============================================================================

# ==============================================================================
# DEPENDENCIES : 
# 	NAME	   : Dependency name
# 	LOCATION   : path/to/dependency
# 	INSTALL	   : any install instructions
# 	PURPOSE	   : what it does
# ==============================================================================

# ==============================================================================
# CONFIGURATION:
# ==============================================================================

$ConfigFile = Join-Path (Split-Path $PSScriptRoot -Parent) "dashboard-config.ps1"
if (Test-Path $ConfigFile) { . $ConfigFile }

$cfg = $Global:DashboardConfig

$OptionId    = "my-task"
$TaskName    = "Execute Utility Task"

# TEMP / CONFIG HOOK: Pull environment paths directly from $cfg with safe defaults
$TargetDir   = if ($cfg -and $cfg.RootDir) { $cfg.RootDir } else { Split-Path $PSScriptRoot -Parent }
$VenvPython  = if ($cfg -and $cfg.VenvPython) { $cfg.VenvPython } else { Join-Path $TargetDir "venv\Scripts\python.exe" }
$TaskScript  = Join-Path $TargetDir "scripts\task.py"

# TEMP / OPTIONAL: Status history file integration (e.g. "task.status" written as "OK|timestamp|info")
$StatusFile  = Join-Path $TargetDir "task.status"

# ==============================================================================

@{
    Id        = $OptionId
    Title     = $TaskName
    Order     = $OptionOrder

    GetState  = ({ "RUN" }).GetNewClosure()

    GetStatus = ({
        # Optional: Check status history file if generated by the script
        if (Test-Path $StatusFile) {
            try {
                $raw = Get-Content $StatusFile -Raw
                if ($raw) {
                    $parts = $raw.Trim().Split('|')
                    $state = $parts[0]
                    $time  = if ($parts.Count -ge 2) { $parts[1] } else { "Unknown" }
                    $info  = if ($parts.Count -ge 3) { $parts[2] } else { "" }

                    if ($state -in @("OK", "SYNCED", "SUCCESS")) {
                        return @{ Text = "  [ SYNCED  ] $($TaskName.PadRight(25)) (Last: $time | $info)"; Color = "Green" }
                    } elseif ($state -eq "ERROR") {
                        return @{ Text = "  [ FAILED  ] $($TaskName.PadRight(25)) (Last: $time | $info)"; Color = "Red" }
                    }
                }
            } catch {}
        }

        # Fallback static script readiness check
        $exists = Test-Path $TaskScript
        $text = if ($exists) { 
            "  [ READY   ] $($TaskName.PadRight(25)) (Script Ready)" 
        } else { 
            "  [ ERROR   ] $($TaskName.PadRight(25)) (Script Missing)" 
        }
        return @{ Text = $text; Color = if ($exists) { "Cyan" } else { "Red" } }
    }).GetNewClosure()

    Execute   = ({
        # Run global backup hook if loaded into current PowerShell session
        if (Get-Command "Backup-OdysseusData" -ErrorAction SilentlyContinue) {
            Write-Host "`n  Backing up database and vector store..." -ForegroundColor DarkGray
            Backup-OdysseusData
        }

        if (Test-Path $TaskScript) {
            Write-Host "`n  Executing $TaskName..." -ForegroundColor Cyan
            & "$VenvPython" "$TaskScript"
        } else {
            Write-Host "`n  [ ERROR ] Task script not found at: $TaskScript" -ForegroundColor Red
        }

        Write-Host "`n  Press ANY KEY to return to dashboard..." -ForegroundColor Gray
        $null = [Console]::ReadKey($true)
    }).GetNewClosure()
}